### ISSUE TITLE
Alternate Dimension Edits

### ISSUE THREAD

**Issue by comptonb37** [Mitchello457/Mitchello457.github.io#2]
Just some quick edits for your post "Thinking in an Alternate Dimension"

Punctuation/Grammar/Spelling (Quick Fixes):
- The sentence talking about GLaDOS may need to be revised to "keep you company, but she doesn’t help you; she..."
- In the sentence about the puzzle being a fork, you capitalized the o in "one"

Sentence Structure:
- The sentence before the fork in the road would probably sound better worded as "but that would consume more time than someone would be willing to spend."

Also make sure you don't forget your TL;DR section, nice job overall

**Comment by Mitchello457** [comment]
All of these issues have been addressed. Thank you for the feedback.
