### ISSUE TITLE
The Dulling of Skillets

### ISSUE THREAD

**Issue by jonathanwmendez** [Mitchello457/Mitchello457.github.io#3]
Here are somethings I think you can do to improve your writing:

- "What would someone do if you were stuck on a homework problem?" second paragraph first sentence. I think this sentence can be restructured by changing "you" with "they" because you restricts "someone" to solely the reader.

-  **Second paragraph, second sentence:** may want to reword for flow but this one is up to you because its difficult to work around.

- **Middle of the second paragraph:** "Having so much information available make it easy to just be shown what to do." the word "make" should be plural. Also, I feel there is a strong way to get the same point across from this sentence, which can also improve flow.

- **Middle of the paragraph:** "People when memorize how to do that one specific type of example and ignore what other problems could arise." This sentence is extremely choppy to the readers perspective due to grammatical phrasing causing you point here to be lost.

-  **Second paragraph:** "It seems that many people memorize the information and then forget it on the test." The same thing can be said with fewer words which will make this stronger and improve flow.

-  I feel that the last two sentences of paragraph two are confusing due to the use of excess words that interrupts the flow and the point that you are trying to get across here.

- Overall with paragraph two there is a lot of flow interrupted by cluttered sentences and grammatical phrases that aren't clear. These things can be improved by correcting the grammatical errors and reword sentences. You do a good job at connecting immediately to your education topic however it becomes confusing when swap back and forth from homework to tests at the very end. I understand that you are using "tests" as a type of climax point for the education aspect of this essay, however it is slightly confusing and could use more clarification.

- **First sentence, third paragraph:** "Video not are meant to be easy." This statement doesn't make sense.

- **Third sentence, third paragraph:** "Many players are not adept at playing these games so most games accommodate an easier gameplay for those that are new and a harder gameplay for those that are veterans." I feel as the reader that this sentence would be best broken up into two different sentences because having them together makes it very confusing to at first and interrupts flow.

- **Middle of paragraph three:** "As the name suggests, it is full of a poisonous swamp and there are many enemies that will poison you out of no where." The words "no where" should be one word: "nowhere"

- **Bottom of paragraph three** "There are those that try as many times as needed until the are is complete. The word "are" should be "area".

- **Bottom of paragraph three:** "This avenue doesn’t tech the user how to deal with tough situations." The word "tech" should be "teach".

- **Bottom of paragraph four:** "they should know the general direction that they have to head in."
They should be capitalized.

- **Last paragraph:** "Someone should use this information to learn the skills needed to succeed in activities such as homework, video game, and traveling." "video game" should be plural here or use of the word "video gaming".

- **Last paragraph:** "Everyone will need help with one thing or another but the world needs to think before the fall back on the internet." I think that the word "the" should be replaced by "it" and "falls" because you have the noun the "world" but the rest of the sentence should be referring to the world, otherwise it gives the possibility of a different intake.

**Comment by Mitchello457** [comment]
Thank you. All of these issues have been addressed.
