### ISSUE TITLE
Editing for piracy writing

### ISSUE THREAD

**Issue by cerdamejiaj** [Mitchello457/Mitchello457.github.io#6]
First Paragraph
- You need capital A in when you start a new sentence in At least to him
- You need space between money and which 

Second Paragraph
- every day should go together and also song writer
- when you said "Concert's" did you meant Concerts ?
- in as pirating did you meant aspirating ?

Third Paragraph
- You have "It they" did you meant "If they" ?
-You have all twice 
add "the" before time and also misspelled people after "time that"

Fourth Paragraph 
in the last sentence did you meant "artist's" ?

Your aritcle is overall great, its pretty detailed and well writen.

**Comment by Mitchello457** [comment]
Thank you for the feedback. I made all of the changes named except for Three. Every day will stay as two words because I could have said each day instead, as pirating will remain, and it should still be of time that people spend.
