### ISSUE TITLE
Edits for: Students Without an Education

### ISSUE THREAD

**Issue by cerdamejiaj** [Mitchello457/Mitchello457.github.io#7]
**Paragraph 1**
**Sentence**: "The answer to these questions are yes and plagiarism respectively"
You need to change this sentence around, it's not very clear. You can say something along this lines;
The answer to these questions are that yes our work is protected, but plagiarism is a constant threat.

**Sentence:** "These people have work done for them and in turn are not being prepared for the outside world." Same thing here, not very clear. Did you mean in return?
You can say: in return, they are learning any skill that will help them in the outside world.

**Paragraph 2**
**Sentence:** "his occupation was revealed to public" you should add "the public"

Edit: change "three page" to three-page

Edit: change seventy-five page to seventy-five-page 

Edit: change twenty page to twenty-page 

Edit: "it is not difficult the write... " remove "the" and put "to"

Edit: change "work load" it goes together

 Try breaking down your second paragraph, it way too long, readers would lose interest in reading your artcle.

**Comment by Mitchello457** [comment]
Thank you for the feedback. I will be making these changes momentarily and will close the issue when it is completed.
